import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF7F2',
    paddingHorizontal: 28,
    alignItems: 'center',
  },
  homeHeader: {
    width: '100%',
    alignItems: 'center',
    flexShrink: 0,
  },
  modeScroll: {
    flex: 1,
    width: '100%',
  },
  modeScrollContent: {
    flexGrow: 1,
    width: '100%',
    alignItems: 'center',
    paddingTop: 4,
    paddingBottom: 8,
  },
  logo: {
    width: '100%',
    maxWidth: 300,
    height: 70,
    marginBottom: 12,
    resizeMode: 'contain',
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    color: '#2E2E2E',
    letterSpacing: -1.5,
    textAlign: 'center',
    marginBottom: 8,
  },
  chooseModeLabel: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    lineHeight: 22,
    width: '100%',
  },
  highScoreRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    marginTop: 16,
    backgroundColor: '#F0EDE8',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
  },
  highScoreLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  highScoreValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#3D3D3D',
  },
  spacer: { flex: 1 },
  howTo: {
    width: '100%',
    marginBottom: 32,
    gap: 10,
  },
  howToRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 4,
    flexShrink: 0,
  },
  howToText: {
    flex: 1,
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  btn: {
    width: '100%',
    minHeight: 56,
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A2A2A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 8,
  },
  btnPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
    shadowOpacity: 0.1,
    elevation: 4,
  },
  btnText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FAF7F2',
    letterSpacing: 0.4,
  },
  btnSecondary: {
    width: '100%',
    minHeight: 48,
    marginTop: 12,
    paddingVertical: 13,
    paddingHorizontal: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#C8C4BE',
  },
  btnSecondaryPressed: {
    opacity: 0.7,
  },
  btnSecondaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
    letterSpacing: 0.3,
  },

  modeMenu: {
    width: '100%',
    gap: 12,
    paddingTop: 8,
  },
  modeCard: {
    width: '100%',
    backgroundColor: '#F0EDE8',
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#E8E4DE',
  },
  modeCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  modeName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2E2E2E',
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  modeDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  modeBestRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0DCD4',
  },
  modeBestLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#AAA',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  /** Slide card: “Best” in title case, not all-caps */
  modeBestLabelPlain: {
    fontSize: 11,
    fontWeight: '700',
    color: '#AAA',
    letterSpacing: 0.8,
  },
  modeBestValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#3D3D3D',
  },
});
