import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAF7F2',
    paddingHorizontal: 28,
    alignItems: 'center',
  },
  dotsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 24,
  },
  dot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  gameOverTitle: {
    fontSize: 42,
    fontWeight: '800',
    color: '#2E2E2E',
    letterSpacing: -1.5,
    textAlign: 'center',
  },
  scoreCard: {
    marginTop: 32,
    width: '100%',
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 4,
  },
  scoreLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#AAA',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  scoreValue: {
    fontSize: 64,
    fontWeight: '800',
    color: '#2E2E2E',
    letterSpacing: -3,
    marginTop: 2,
  },
  newBest: {
    fontSize: 14,
    fontWeight: '700',
    color: '#A8D8C9',
    marginTop: -4,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  divider: {
    width: 40,
    height: 1,
    backgroundColor: '#EEE',
    marginVertical: 14,
  },
  bestLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#CCC',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  bestValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#AAA',
    letterSpacing: -1,
    marginTop: 2,
  },
  spacer: { flex: 1 },
  buttons: {
    width: '100%',
    gap: 14,
  },
  adWrap: {
    width: '100%',
    marginTop: 8,
    marginBottom: 12,
    minHeight: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnPrimary: {
    width: '100%',
    minHeight: 56,
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A2A2A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 8,
  },
  btnPrimaryPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
    shadowOpacity: 0.1,
    elevation: 4,
  },
  btnPrimaryText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FAF7F2',
    letterSpacing: 0.35,
  },
  btnSecondary: {
    width: '100%',
    minHeight: 50,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderWidth: 1.5,
    borderColor: '#D8D4CC',
  },
  btnSecondaryPressed: {
    backgroundColor: 'rgba(0,0,0,0.05)',
    transform: [{ scale: 0.98 }],
  },
  btnSecondaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#5A5A5A',
    letterSpacing: 0.2,
  },
});
